# Generated by Django 3.1.6 on 2021-02-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=120)),
                ('accno', models.CharField(max_length=15, unique=True)),
                ('acctype', models.CharField(max_length=120)),
                ('balance', models.IntegerField(default=3000)),
                ('phonenumber', models.IntegerField()),
                ('mpin', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transferdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpin', models.CharField(max_length=6)),
                ('accno', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
