# Generated by Django 3.1.6 on 2021-02-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210205_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='accno',
            field=models.IntegerField(),
        ),
    ]
